// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvqbukykzlvfkguwmdgv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2cWJ1a3lremx2ZmtndXdtZGd2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTg1MzIsImV4cCI6MjA1OTg3NDUzMn0.BDWVFQtW5wM76AP9O6N-73HDUjK6w2CyqvqYyPpg8Gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);